# Generated by Django 3.0.2 on 2020-01-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_inter',
            name='inter',
            field=models.ForeignKey(on_delete=models.Model, to='logbookapp.Internship', verbose_name='کارآموزی ها'),
        ),
    ]
